### ISSUE TITLE
Gulp?

### ISSUE THREAD

**Issue by ghengeveld** [accommodavid/spooky-react#1]
If this is a minimalistic, i-don't-make-assumptions skeleton, why are you including Gulp? You can get by perfectly fine by [just using npm scripts](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/). For watching, you can use [npm-scripts-watcher](https://github.com/wehkamp/npm-scripts-watcher#npm-scripts-watcher).

**Comment by accommodavid** [comment]
The purpose of this skeleton is not to literally have as little things included as possible. It's to get you up and running with React and ES6 in a way that doesn't force you into a setup you're unfamiliar with, so you can add your own stuff easier and get to actual building quicker. Most people know Gulp. Fewer people will know how to extend a skeleton that only uses npm scripts.

Since ES6 will likely already be 'the new thing' for most people right now, I want to avoid adding more 'new things'. In fact, the whole reason I created this skeleton was because I got a little tired of all the other skeletons out there including techniques and components that were released like two days ago. 

The idea behind this skeleton is that you use it to set up a React application quickly, using the tools you already know, then start getting familiar with using it in tandem with ES6 and than have the space to extend it in your own way.

**Comment by ifraixedes** [comment]
@ghengeveld do you know how to setup with npm-scripts easily? then it will be good to fork this and have that different flavour. This one can stay as @accommodavid and we'll get the good things of the diversity.

Thanks both.

**Comment by accommodavid** [comment]
:+1: That's a really good idea. Then I'll also put a link to the forked repo in the README, so people can pick and choose easily.

**Comment by orjantufte** [comment]
I think its fine, i love gulp btw and i think it should be included as you should at least include one task runner.

**Comment by accommodavid** [comment]
@ghengeveld let me know if you plan on forking the repo. in any case i'll close this issue.

**Comment by ghengeveld** [comment]
To be honest I don't feel like creating yet another skeleton. Besides that I really don't have the time. Someone else is free to do so though.
